# This name is for reference.
name = "questoot"

# This tells Pages where the front-end build output is.
pages_build_output_dir = "dist"

[durable_objects]
bindings = [
  # The script_name is a special reference to the Functions service
  # that Pages builds from your /functions directory.
  { name = "GAME_ROOM", class_name = "GameRoom", script_name = "functions" }
]