name = "questoot-api"
main = "quiz-quest/functions/api/game.ts"
compatibility_date = "2023-10-30"

# This new line is the key to the fix
pages_build_output_dir = "dist"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]